site_name: lua-CoatPersistent
site_description: an ORM for lua-Coat
site_author: François Perrad
repo_url: https://github.com/fperrad/lua-CoatPersistent
pages:
- Home: index.md
- API:
  - Coat.Persistent: persistent.md
  - Coat.Persitent.lsqlite3: sqlite3.md
theme: mkdocs
copyright: Copyright &copy; 2010-2018 Fran&ccedil;ois Perrad
