
doc.css:
	wget https://raw.githubusercontent.com/keplerproject/kepler/master/css/doc.css

check:
	xmllint --noout --valid index.html
	xmllint --noout --valid persistent.html
	xmllint --noout --valid lsqlite3.html

